spring.application.name=party-tracker

## MSSQL Configuration
#spring.datasource.url=jdbc:sqlserver://DHSKLPDTAI291;instanceName=SQLEXPRESS;databaseName=party;encrypt=true;trustServerCertificate=true
#spring.datasource.username=user
#spring.datasource.password=Strongpassword@123
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
##sourav
##spring.datasource.url=jdbc:sqlserver://DHSKLPDTAI290;instanceName=SQLEXPRESS;databaseName=party;encrypt=true;trustServerCertificate=true
##
##spring.datasource.username=user
##spring.datasource.password=Strongpassword123
##spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
## JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.zdzveujqjulwwyhcamhp
spring.datasource.password=Sunikuttan@123

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## Server
#server.port=8081

# CORS
app.cors.allowed-origins=http://localhost:3000
server.port=${PORT:8080}

# Admin Password (change in production)
app.admin.password=admin123
